config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :claims, only: [:create, :destroy, :update, :edit]
  end
  devise_for :users

  root 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :claims, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :claims
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :authenticate_user!

  def create
    @company = Company.find(params[:company_id])
		@claim = Claim.new(description:params[:claim][:description], user: current_user)
		@company.claims << @claim
		@claim.save
  end

  def destroy
		@company = Company.find(params[:company_id])
		@claim = Claim.find(params[:id])
		@claim.destroy
	end

	def edit
		@company = Company.find(params[:company_id])
		@claim = Claim.find(params[:id])
	end

	def update
		@claim = Claim.find(params[:id])
		@claim.update(content: params[:claim][:description])
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @claims = Claim.all
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.save
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company.update(company_params)
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/claims/_claim.html.erb
<div class="well well-sm" id="<%= @claim.id %>">
  <strong><%= @claim.description %></strong>
  <br>
  <div class="text-right">
    <%= link_to 'Editar', edit_company_claim_path(@company, @claim), data: { remote: true }, class: 'btn btn-xs btn-success' %>
    <%= link_to 'Eliminar', company_claim_path(@company, @claim), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar la compañia?', remote: true }, class: 'btn btn-xs btn-danger' %>
  </div>
</div>

app/views/claims/_form.html.erb
<%= form_with(model: [@company, @claim], html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <div class="col-md-12">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit 'Confirmar', class: 'btn btn-primary' %>
<% end %>

app/views/claims/create.js.erb
$('#claims').append("<%= j render 'claim' %>");
$("[name='claim[description]']").val('');

app/views/claims/destroy.js.erb
$("#<%= @claim.id %>").toggle(200);

app/views/claims/edit.js.erb
$('#claim_edit').html("<%= j render 'form' %>")

$('#exampleModal').modal('show');

app/views/claims/update.js.erb
$('#contenido<%= @company.id %>').text('<%= @claim.description %>');

$('#exampleModal').modal('hide');

app/views/companies/_company.html.erb
<div class="well well-sm" id="<%= @company.id %>">
  <strong><%= @company.name %></strong>
  <br>
  <div class="text-right">
    <!-- Button trigger modal -->
    <%= link_to 'Show', company_path(@company), class: 'btn btn-xs btn-warning' %>
    <%= link_to 'Editar', edit_company_path(@company), data: { remote: true }, class: 'btn btn-xs btn-success' %>
    <%= link_to 'Eliminar', company_path(@company), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar esta Compañía?', remote: true }, class: 'btn btn-xs btn-danger' %>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Compañia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="comapany_edit">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: @company, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <div class="col-md-12">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit 'Confirmar', class: 'btn btn-primary' %>
<% end %>

app/views/companies/create.js.erb
$('#companies').append("<%= j render 'company' %>");
$("[name='company[name]']").val('');

app/views/companies/destroy.js.erb
$("#<%= @company.id %>").toggle(200);

app/views/companies/edit.js.erb
$('#company_edit').html("<%= j render 'form' %>")

$('#exampleModal').modal('show');

app/views/companies/index.html.erb
<div class="text-center">
	<p id="notice"><%= notice %></p>
</div>

<div class="row">
	<div class="col-md-4">
		<div class="well well-sm">
			<legend>Crear Nueva Compañia</legend>
			<%= form_with(model: [@company, Company.new], html: { class: 'form-horizontal' }) do |f| %>
				<div class="form-group">
					<div class="col-md-12">
						<%= f.text_field :name, placeholder: 'Nombre', class: 'form-control' %>
					</div>
				</div>
				<%= f.submit 'Aceptar', class: 'btn btn-xs btn-primary' %>
			<% end %>

		</div>
	</div>
	<div class="col-md-8" id="companies">
		<% @companies.each do |company| %>
			<div class="well well-sm" id="<%= company.id %>">
				<strong><%= company.name %></strong>
				<br>
				<div class="text-right">
					<!-- Button trigger modal -->
          <%= link_to 'Show', company_path(company), class: 'btn btn-xs btn-warning' %>
					<%= link_to 'Editar', edit_company_path(company), data: { remote: true }, class: 'btn btn-xs btn-success' %>
					<%= link_to 'Eliminar', company_path(company), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar esta Compañía?', remote: true }, class: 'btn btn-xs btn-danger' %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Compañia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="company_edit">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<div class="text-center">
	<p id="notice"><%= notice %></p>

	<div class="jumbotron">
		<p>
	  	<%= @company.name %>
		</p>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="well well-sm">
			<legend>Ingresar Reclamo</legend>
			<%= form_with(model: [@company, Claim.new], html: { class: 'form-horizontal' }) do |f| %>
				<div class="form-group">
					<div class="col-md-12">
						<%= f.text_area :description, placeholder: 'Escribe tu reclamo aquí...', class: 'form-control' %>
					</div>
				</div>
				<%= f.submit 'Enviar', class: 'btn btn-primary' %>
			<% end %>

		</div>
	</div>
	<div class="col-md-8" id="claims">
		<% counter = 0 %>
		<% @claims.each do |claim| %>
			<div class="well well-sm" id="<%= claim.id %>">
				#<%= counter += 1 %>
				<strong><%= claim.user.email %>:</strong>
				<br>
				<div id="contenido<%= claim.id %>">
					<%= claim.description %>
				</div>
				<div class="text-right">
					<!-- Button trigger modal -->
					<%= link_to 'Editar', edit_company_claim_path(@company, claim), data: { remote: true }, class: 'btn btn-xs btn-success' %>
					<%= link_to 'Eliminar', company_claim_path(@company, claim), method: :delete, data: { confirm: 'Estás seguro que deseas eliminar el Comentario?', remote: true }, class: 'btn btn-xs btn-danger' %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Comentario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="comment_edit">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finally</title>
    <%= csrf_meta_tags %>

  	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-gv0oNvwnqzF6ULI9TVsSmnULNb3zasNysvWwfT/s4l8k5I+g6oFz9dye0wg3rQ2Q" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script   src="https://code.jquery.com/jquery-3.2.1.min.js"   integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="   crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-default">
  	  <div class="container">
  	    <div class="navbar-header">
  	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  	        <span class="sr-only">Toggle navigation</span>
  	        <span class="icon-bar"></span>
  	        <span class="icon-bar"></span>
  	        <span class="icon-bar"></span>
  	      </button>
          <a class="navbar-brand" href="<%= root_path %>">
  	      	<span>Home</span>
  	      </a>
  	      <a class="navbar-brand" href="#">
  	      	<span>Prototipo</span>
  	      </a>
  	    </div>

  	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  	      <ul class="nav navbar-nav navbar-right">
  	        <% if user_signed_in? %>
  	        	<li><a href="#"><%= current_user.email %>!</a></li>
  	        	<li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></li>
  	        <% else %>
  	        	<li><%= link_to 'Inicia sesión', new_user_session_path %></li>
  	        	<li><%= link_to 'Regístrate', new_user_registration_path %></li>
  	        <% end %>
  	      </ul>
  	    </div>
  	  </div>
	  </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container"><%= yield %></div>

  </body>
</html>